name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: test
      run: |
        echo "Hello World"
        echo $PWD

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    - name: Run gh-pages script
      run: npm run gh-pages
